language: java

dist: trusty

jdk:
  - openjdk11
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "aidanwhiteley-github"

cache:
  directories:
  - $HOME/.m2

script:
  #- git fetch --unshallow
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dspring.profiles.active=default
