spring:
  application:
    name: Books API Gateway
  profiles:
    active: default


books:
  gateway:
    uri: https://cloudybookclub.com
    readOnlyApisPath: /api/**
    updateApisPath: /secure/api/**

    readOnlyThrottleCapacity: 100
    readOnlyThrottleRefillTokens: 20
    readOnlyThrottleRefillPeriod: 20
    readOnlyThrottleRefillTimeUnit: SECONDS

    updateThrottleCapacity: 20
    updateThrottleRefillTokens: 10
    updateThrottleRefillPeriod: 30
    updateThrottleRefillTimeUnit: SECONDS

hystrix:
  command:
    readCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    updateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
server:
  port: 8000
