spring:
  application:
    name: BooksAPIGateway

  profiles:
    active: test

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    service-registry:
      auto-registration:
        enabled: true
        register-management: off
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY}:8761/eureka/

books:
  gateway:
    uri: lb://BooksApiService
    readOnlyApisPath: /api/**
    updateApisPath: /secure/api/**

    readOnlyThrottleCapacity: 100
    readOnlyThrottleRefillTokens: 20
    readOnlyThrottleRefillPeriod: 20
    readOnlyThrottleRefillTimeUnit: SECONDS

    updateThrottleCapacity: 20
    updateThrottleRefillTokens: 10
    updateThrottleRefillPeriod: 30
    updateThrottleRefillTimeUnit: SECONDS

hystrix:
  command:
    readCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    updateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
server:
  port: 8000
