spring:
  application:
    name: BooksAPIGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
    service-registry:
      auto-registration:
        enabled: false
        register-management: false
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

# By default we disable Eureka client functionality even though it is on the classpath
eureka:
  client:
    enabled: false

books:
  gateway:
    #uri: lb://BooksApiService
    uri: https://cloudybookclub.com
    readOnlyApisPath: /api/**
    updateApisPath: /secure/api/**

    readOnlyThrottleCapacity: 100
    readOnlyThrottleRefillTokens: 20
    readOnlyThrottleRefillPeriod: 20
    readOnlyThrottleRefillTimeUnit: SECONDS

    updateThrottleCapacity: 20
    updateThrottleRefillTokens: 10
    updateThrottleRefillPeriod: 30
    updateThrottleRefillTimeUnit: SECONDS

hystrix:
  command:
    readCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    updateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
server:
  port: 8000

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # Exposing only read only items and not large data amounts - so no heapdump, threaddump or shutdown. No project use of flyway, integrationgraph, liquibase, prometheus
        include: auditevents, beans, caches, conditions, configprops, env, health, httptrace, info, jolokia, logfile, loggers, metrics, mappings, scheduledtasks, sessions
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
