spring:
  application:
    name: BooksAPIGateway

  profiles:
    active: test

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    service-registry:
      auto-registration:
        enabled: true
        register-management: off
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY}:8761/eureka/

books:
  gateway:
    uri: lb://BooksApiService
    readOnlyApisPath: /api/**
    updateApisPath: /secure/api/**

    readOnlyThrottleCapacity: 100
    readOnlyThrottleRefillTokens: 20
    readOnlyThrottleRefillPeriod: 20
    readOnlyThrottleRefillTimeUnit: SECONDS

    updateThrottleCapacity: 20
    updateThrottleRefillTokens: 10
    updateThrottleRefillPeriod: 30
    updateThrottleRefillTimeUnit: SECONDS

hystrix:
  command:
    readCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    updateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
server:
  port: 8000

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # Exposing only read only items and not large data amounts - so no heapdump, threaddump or shutdown. No project use of flyway, integrationgraph, liquibase, prometheus
        include: auditevents, beans, caches, conditions, configprops, env, health, httptrace, info, jolokia, logfile, loggers, metrics, mappings, scheduledtasks, sessions
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false