
books:
  gateway:
    uri: https://cloudybookclub.com
    read-only-apis-path: /api/**
    update-apis-path: /secure/api/**

logging:
  level:
    root: warn
    org:
      springframework:
        boot:
          web:
            embedded:
              netty:
                NettyWebServer: info
        cloud:
          gateway:
            handler:
              FilteringWebHandler: debug
    com:
      aidan:
        books: info

hystrix:
  command:
    readCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    updateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
